#!/bin/sh

set -ouex pipefail

cd /etc/yum.repos.d/ && curl -LO https://cli.github.com/packages/rpm/gh-cli.repo 

rpm-ostree install -y gh

sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/gh-cli.repo

