#!/bin/sh

set -ouex pipefail


# if grep -qv "39" <<< "${FEDORA_MAJOR_VERSION}"; then
# if grep -gv "$(rpm -E %fedora)" <<< "${FEDORA_MAJOR_VERSION}" ; then 
if [[ "$(rpm -E %fedora)" != $RAWHIDE ]] ; then
  cd /etc/yum.repos.d/ && curl -L https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-$(rpm -E %fedora)/solopasha-hyprland-fedora-$(rpm -E %fedora).repo -o solopasha-hyprland.repo
else
  cd /etc/yum.repos.d/ && curl -L https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-rawhide/solopasha-hyprland-fedora-rawhide.repo -o solopasha-hyprland.repo
  ls -la
fi


# rpm-ostree install -y hyprland 
rpm-ostree override remove xorg-x11-server-Xwayland --install hyprland

#  hyprland-plugins (is multiple packages to select)
# rpm-ostree override remove waybar
rpm-ostree install -y \
  waybar \
  xdg-desktop-portal-hyprland \
  hyprland-plugins \
  hyprland-contrib \
  hyprland-autoname-workspaces \
  hyprpaper \
  hyprpicker \
  hyprshot  \
  aylurs-gtk-shell \
  eww-wayland-git

sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/solopasha-hyprland.repo
