#!/bin/sh

set -ouex pipefail

cd /etc/yum.repos.d/ && curl -LO https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-$(rpm -E %fedora)/solopasha-hyprland-fedora-$(rpm -E %fedora).repo

# rpm-ostree override remove waybar
rpm-ostree install -y \
  hyprland \
  waybar-hyprland \
  xdg-desktop-portal-hyprland \
  hyprland-plugins \
  hyprland-contrib \
  hyprland-autoname-workspaces \
  hyprpaper \
  hyprpicker \
  hyprshot  \
  eww-wayland-git

hyprland-plugins waybar-hyprland #hyprland-autoname-workspace hyprpaper hyprpicker 

sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/solopasha-hyprland-fedora-$(rpm -E %fedora).repo
