#!/bin/sh

set -ouex pipefail

cd /etc/yum.repos.d/ && curl -LO https://copr.fedorainfracloud.org/coprs/axeld/eww/repo/fedora-38/axeld-eww-fedora-$(rpm -E %fedora).rep
o
rpm-ostree install -y eww

sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/fedora-$(rpm -E %fedora)/axeld-eww-fedora-$(rpm -E %fedora).rep
