#!/bin/sh

set -ouex pipefail

if [[ "$(rpm -E %fedora)" != $RAWHIDE ]] ; then
  # cd /etc/yum.repos.d/ && curl -L https://copr.fedorainfracloud.org/coprs/solopasha/libdrm/repo/fedora-$(rpm -E %fedora)/solopasha-libdrm-fedora-$(rpm -E %fedora).repo -o solopasha-libdrm.repo
  cd /etc/yum.repos.d/ && curl -L https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-$(rpm -E %fedora)/solopasha-hyprland-fedora-$(rpm -E %fedora).repo -o solopasha-hyprland.repo
else
  # cd /etc/yum.repos.d/ && curl -L https://copr.fedorainfracloud.org/coprs/solopasha/libdrm/repo/fedora-rawhide/solopasha-libdrm-fedora-rawhide.repo -o solopasha-libdrm.repo
  cd /etc/yum.repos.d/ && curl -L https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-rawhide/solopasha-hyprland-fedora-rawhide.repo -o solopasha-hyprland.repo
  ls -la
fi

if [[ "$(rpm -E %fedora)" != $RAWHIDE ]] ; then
  rpm-ostree install -y hyprland hyprland-plugins waybar
else
  rpm-ostree install -y hyprland-git hyprland-plugins-git waybar-git
fi

rpm-ostree install -y \
  xdg-desktop-portal-hyprland \
  hyprland-contrib \
  hyprland-autoname-workspaces \
  hyprpaper \
  hyprpicker \
  hyprshot  \
  hypridle \
  hyprlock \
  aylurs-gtk-shell \
  eww-git

# sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/solopasha-libdrm.repo
sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/solopasha-hyprland.repo
