#!/bin/sh

set -ouex pipefail

# See:
#   https://rpmfusion.org/Howto/OSTree
rpm-ostree install \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/rpmfusion-nonfree-steam.repo
sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/rpmfusion-nonfree-nvidia-driver.repo

# Install good bluetooth sound (always)
rpm-ostree install pipewire-codec-aptx

#Intel
if [[ "$(rpm -E %fedora)" != $FEDORA_STABLE ]] ; then

  rpm-ostree override remove libva-intel-media-driver --install=intel-media-driver
#   #  libva-intel-drivers libva-utils
else
  rpm-ostree install intel-media-driver
fi

#AMD
rpm-ostree override remove mesa-va-drivers --install mesa-va-drivers-freeworld.x86_64


# if [[ "$(rpm -E %fedora)" != $FEDORA_BETA   &&  "$(rpm -E %fedora)" != $RAWHIDE ]] ; then

  # installing mozilla-openh264 seems to be the only way to get ffmpey to install

  # sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/fedora-cisco-openh264.repo

  rpm-ostree override remove \
    ffmpeg-free \
    libavcodec-free \
    libavdevice-free \
    libavfilter-free \
    libavformat-free \
    libavutil-free \
    libpostproc-free \
    libswresample-free \
    libswscale-free \
    --install \
        ffmpeg

  # rpm-ostree override remove \
  #   libavcodec-free \
  #   libavfilter-free \
  #   libavformat-free \
  #   libavutil-free \
  #   libpostproc-free \
  #   libswresample-free \
  #   libswscale-free \
  #   --install=ffmpeg\
  #   --install=ffmpeg-libs.x86_64 \
  #   --install=libavcodec-freeworld \
  #   --install=mozilla-openh264

  # sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/fedora-cisco-openh264.repo

  # rpm-ostree install gstreamer1-plugin-libav gstreamer1-plugins-bad-free-extras gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly gstreamer1-vaapi
# fi

# sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/rpmfusion-free.repo
# sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/rpmfusion-free-updates.repo
# sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/rpmfusion-nonfree.repo
# sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
