#!/bin/sh

set -ouex pipefail

cd /etc/yum.repos.d/ && curl -LO https://copr.fedorainfracloud.org/coprs/atim/bottom/repo/fedora-$(rpm -E %fedora)/atim-bottom-fedora-$(rpm -E %fedora).repo

rpm-ostree install -y bottom

sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/atim-bottom-fedora-38.repo
